### ISSUE TITLE
自问

### ISSUE THREAD

**Issue by Xovee** [Xovee/uestc-course#66]
有什么办法能让不能翻墙的同学快速的访问 GitHub 的资源呢？

**Comment by wqyg18** [comment]
可以使用网盘吗?比如蓝奏云什么的,然后在河畔立一个帖子,放上链接?

**Comment by Xovee** [comment]
> 可以使用网盘吗?比如蓝奏云什么的,然后在河畔立一个帖子,放上链接?

更新、同步起来不太方便

**Comment by wqyg18** [comment]
那或者考虑gitee?

**Comment by Xovee** [comment]
> 那或者考虑gitee?

O(∩_∩)O，maybe，我试一下

**Comment by Xovee** [comment]
> 那或者考虑gitee?

试了一下，个人版gitee不能导入或同步仓库（因为仓库太大了），企业版才可以。

**Comment by LolipopJ** [comment]
> 更新、同步起来不太方便

依赖于 Github 进行版本管理的话，目前是有一些加速站点是可用的，例如 [FastGit](https://doc.fastgit.org/zh-cn/)。底层应该是使用 Nginx 反代加速，相当于借用别人的服务器下载。

最简单的方式应该是，使用[这个 Chrome 插件](https://github.com/fhefh2015/Fast-GitHub)。从用户角度解决问题。

此外我找到了一个讨论：[GitHub中国加速访问](https://github.com/chenxuhua/issues-blog/issues/3)，可以参考。

**Comment by Xovee** [comment]
> > 更新、同步起来不太方便
> 
> 依赖于 Github 进行版本管理的话，目前是有一些加速站点是可用的，例如 [FastGit](https://doc.fastgit.org/zh-cn/)。底层应该是使用 Nginx 反代加速，相当于借用别人的服务器下载。
> 
> 最简单的方式应该是，使用[这个 Chrome 插件](https://github.com/fhefh2015/Fast-GitHub)。从用户角度解决问题。
> 
> 此外我找到了一个讨论：[GitHub中国加速访问](https://github.com/chenxuhua/issues-blog/issues/3)，可以参考。

Got! Many thanks!
我回头再尝试尝试。

**Comment by Goatzy666** [comment]
请问考研目录现在是已经删除了吗

**Comment by Xovee** [comment]
对，本来也只有信软的目录。资源太少了，我本人是没空去各大网站爬的。干脆就删除了

**Comment by zzxupp** [comment]
这个还是用户自行解决为好。为了学习和考试，学习一些日常小技巧是非常用的😁😁😁

**Comment by Xovee** [comment]
> 这个还是用户自行解决为好。为了学习和考试，学习一些日常小技巧是非常用的

哈哈哈哈道理是这个道理，计算机专业的同学还好，其他专业的就可能摸不着头脑了。

**Comment by Ma-lele** [comment]
steam++软件加速github好使

**Comment by mobyw** [comment]
是否考虑构建文件索引网页并部署到 Github Pages，这样可以不用翻墙访问目录，只需在文件下载 URL 上加上代理（如 `ghproxy.com`）即可实现墙内下载。

可以参考：[SWJTU-Courses仓库](https://github.com/swjtuhub/SWJTU-Courses) [索引网站](https://swjtuhub.cn/)

参考 Action:
```yaml
name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install md-index
        run: pip install md-index

      - name: Install mkdocs
        run: pip install mkdocs

      - name: Build index
        run: md-index --url-prefix="https://ghproxy.com/https://raw.githubusercontent.com/Xovee/uestc-course/main/"
        working-directory: "./"

      - name: Build website
        run: mkdocs build
        working-directory: "./"

      - name: Upload build folder to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: "./site"
```
